/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import controller.ControllerAcesso;
import java.awt.AWTException;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import model.ModelAcesso;

/**
 *
 * @author Maycon
 */
public class TesteJframe extends javax.swing.JFrame {


    /**
     * Creates new form TesteJframe
     */
    public TesteJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteJframe().setVisible(true);
            }
        });
    }
private void Teste() {
        ImageIcon icone = new ImageIcon("./src/Icons/Modulos/Menu.png");
        setDefaultCloseOperation(HIDE_ON_CLOSE); // Define o modo de fechamento
        SystemTray tray = SystemTray.getSystemTray();
        TrayIcon trayIcon = new TrayIcon(icone.getImage());
        trayIcon.setImageAutoSize(true);

        /**
         * Instancia um mouse listener para ser usado no TrayIcon
         */
        MouseListener mlOpcoes = new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
               
                // initComponents();
            }

            public void mousePressed(MouseEvent e) {
                JOptionPane.showMessageDialog(rootPane, "teste 2");

            }

            public void mouseReleased(MouseEvent e) {
                /**
                 * Se o mouse for clicado com a roda do mouse ou com o botão
                 * direito fechará a aplicação.
                 */
                if (e.getButton() == 2 || e.getButton() == 3) {

                    System.exit(0);

                }

            }

            public void mouseEntered(MouseEvent e) {
                JOptionPane.showMessageDialog(rootPane, "teste 3");
            }

            public void mouseExited(MouseEvent e) {
            }
        };
        // adiciona o mouseListener no TrayIcon
        trayIcon.addMouseListener(mlOpcoes);

        try {
            // Adiciona o Ícone no SystemTray
            tray.add(trayIcon);
        } catch (AWTException e) {
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
