/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.ControllerCidades;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelCidades; 

/**
 *
 * @author Maycon
 */
public class viewPesquisarCidTransp extends javax.swing.JInternalFrame {

    ControllerCidades controllerCidades = new ControllerCidades();
    ModelCidades modelCidades = new ModelCidades();
    ArrayList<ModelCidades> listaModelCidades = new ArrayList<>();
    
    /**
     * Creates new form ViewFuncaoCadPesquisaCidades
     */
    public viewPesquisarCidTransp() {
        initComponents();
      //  carregarCidades();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCidades = new javax.swing.JTable();
        jtfPesquisar = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Pesquisar - Cidades");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtbCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "tesd"}
            },
            new String [] {
                "ID", "Setor"
            }
        ));
        jtbCidades.getTableHeader().setReorderingAllowed(false);
        jtbCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCidades);
        if (jtbCidades.getColumnModel().getColumnCount() > 0) {
            jtbCidades.getColumnModel().getColumn(0).setMinWidth(60);
            jtbCidades.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbCidades.getColumnModel().getColumn(0).setMaxWidth(60);
            jtbCidades.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        jtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarActionPerformed(evt);
            }
        });
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Cidade" }));

        jLabel1.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtbCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCidadesMouseClicked
        int index = jtbCidades.getSelectedRow();
        TableModel model = jtbCidades.getModel();

        String id = model.getValueAt(index, 0).toString();
        String Cidade = model.getValueAt(index, 1).toString();
        viewCadTransp.jtfIdCidade.setText(id);
        viewCadTransp.jtfNomeCidade.setText(Cidade);
        dispose();
    }//GEN-LAST:event_jtbCidadesMouseClicked

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        PesquisaCidades();
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void PesquisaCidades() {
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbCidades.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbCidades.setRowSorter(classificador);
        String texto = jtfPesquisar.getText();
        String filtro = (String.valueOf(jcbFiltro.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Cidade":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }

    }
    
    
    private void carregarCidades() {
        listaModelCidades = controllerCidades.getListaCidadesController();
        DefaultTableModel modelo = (DefaultTableModel) jtbCidades.getModel();
        modelo.setNumRows(0);
        int cont = listaModelCidades.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelCidades.get(i).getIdCidade(),
                listaModelCidades.get(i).getDescricao()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbFiltro;
    private javax.swing.JTable jtbCidades;
    private javax.swing.JTextField jtfPesquisar;
    // End of variables declaration//GEN-END:variables
}
