/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.BLDatas;
import Tools.Forms;
import Tools.Uppercase;
import static View.viewMainMenu.Desktop;
import controller.ControllerAcesso;
import controller.ControllerPerfil;
import controller.ControllerProximos;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.ModelAcesso;
import model.ModelPerfil;
import model.ModelProximos;

/**
 *
 * @author Maycon
 */
public class viewCadPerfil extends javax.swing.JInternalFrame {

    ControllerPerfil controllerPerfil = new ControllerPerfil();
    ModelPerfil modelPerfil = new ModelPerfil();

    ControllerAcesso controllerAcesso = new ControllerAcesso();
    ModelAcesso modelAcesso = new ModelAcesso();
    ArrayList<ModelAcesso> listaModelAcesso = new ArrayList<>();

    ControllerProximos controllerProximos = new ControllerProximos();
    ModelProximos modelProximos = new ModelProximos();

    BLDatas bLDatas = new BLDatas();
    Uppercase uppercase = new Uppercase();
    Forms forms = new Forms();

    /**
     * Creates new form viewCadPerfil
     */
    public viewCadPerfil() {
        initComponents();
        setProximo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbConfig1 = new javax.swing.JComboBox();
        jcbConfig2 = new javax.swing.JComboBox();
        jcbConfig3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jcbConfig4 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jcbCliente1 = new javax.swing.JComboBox();
        jcbCliente2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbCliente3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("ID:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Status:");

        jtfID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfID.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfID.setEnabled(false);

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Configure as permissões na próxima aba,");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("por padrão, todas virão como Não permitidas.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDescricao)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 184, Short.MAX_VALUE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cabeçalho", jPanel2);

        jLabel4.setText("1 - Cadastrar/Alterar Usuário:");

        jLabel5.setText("2 - Cadastrar/Alterar Área:");

        jLabel6.setText("3 - Cadastrar/Alterar Perfil:");

        jcbConfig1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbConfig1.setSelectedIndex(1);

        jcbConfig2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbConfig2.setSelectedIndex(1);

        jcbConfig3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbConfig3.setSelectedIndex(1);

        jLabel7.setText("4 - Cadastrar/Alterar Empresa:");

        jcbConfig4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbConfig4.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbConfig1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbConfig2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbConfig3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbConfig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbConfig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbConfig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Configurações", jPanel4);

        jLabel10.setText("1 - Cadastrar/Alterar Cliente:");

        jcbCliente1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbCliente1.setSelectedIndex(1);

        jcbCliente2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbCliente2.setSelectedIndex(1);

        jLabel11.setText("2 - Cadastrar/Alterar Vendedor:");

        jLabel12.setText("3 - Visualizar Relatórios:");

        jcbCliente3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "N" }));
        jcbCliente3.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbCliente1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbCliente2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcbCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcbCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcbCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cliente", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Permissões", jPanel3);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salvarPerfil();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        viewMainUsuario.jTabbedPane1.setSelectedIndex(0);
        viewMainUsuario ViewMainUsuario = new viewMainUsuario();
        Desktop.add(ViewMainUsuario);
        forms.centralizaForm(ViewMainUsuario);
        ViewMainUsuario.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = viewMainMenu.Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    private void salvarPerfil() {
        int codigoPerfil, status = 0, statusConfig = 0, statusCliente = 0;

        String config = uppercase.Uppercase("Configurações");
        modelPerfil = controllerPerfil.getPerfilVerificaDuplicidadeController(jtfDescricao.getText());

        if (modelPerfil.getCount() > 0) {
            JOptionPane.showMessageDialog(this, "Já existe um cadastro com essa descrição. Por favor, verifique.!!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            modelPerfil.setIdperfil(Integer.parseInt(jtfID.getText()));
            // modelPerfil.setPerNome(jtfDescricao.getText());
            modelPerfil.setStatus(WIDTH);
            String filtro = jcbStatus.getSelectedItem().toString();
            switch (filtro) {
                case "Ativo":
                    status = 1;
                    break;
                case "Inativo":
                    status = 0;
                    break;
            }
            modelPerfil.setStatus(status);

            //Configuracoes
            modelAcesso.setNome(config);
            modelAcesso.setIdkey("1");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro1 = jcbConfig1.getSelectedItem().toString();
            switch (filtro1) {
                case "S":
                    statusConfig = 1;
                    break;
                case "N":
                    statusConfig = 0;
                    break;
            }
            modelAcesso.setAuth(statusConfig);
            listaModelAcesso.add(modelAcesso);

            modelAcesso = new ModelAcesso();
            modelAcesso.setNome(config);
            modelAcesso.setIdkey("2");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro2 = jcbConfig2.getSelectedItem().toString();
            switch (filtro2) {
                case "S":
                    statusConfig = 1;
                    break;
                case "N":
                    statusConfig = 0;
                    break;
            }
            modelAcesso.setAuth(statusConfig);
            listaModelAcesso.add(modelAcesso);

            modelAcesso = new ModelAcesso();
            modelAcesso.setNome(config);
            modelAcesso.setIdkey("3");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro3 = jcbConfig3.getSelectedItem().toString();
            switch (filtro3) {
                case "S":
                    statusConfig = 1;
                    break;
                case "N":
                    statusConfig = 0;
                    break;
            }
            modelAcesso.setAuth(statusConfig);
            listaModelAcesso.add(modelAcesso);

            modelAcesso = new ModelAcesso();
            modelAcesso.setNome(config);
            modelAcesso.setIdkey("4");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro4 = jcbConfig4.getSelectedItem().toString();
            switch (filtro4) {
                case "S":
                    statusConfig = 1;
                    break;
                case "N":
                    statusConfig = 0;
                    break;
            }
            modelAcesso.setAuth(statusConfig);
            listaModelAcesso.add(modelAcesso);

            modelAcesso = new ModelAcesso();
            modelAcesso.setNome("Cliente");
            modelAcesso.setIdkey("1");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro5 = jcbCliente1.getSelectedItem().toString();
            switch (filtro5) {
                case "S":
                    statusCliente = 1;
                    break;
                case "N":
                    statusCliente = 0;
                    break;
            }
            modelAcesso.setAuth(statusCliente);
            listaModelAcesso.add(modelAcesso);
            modelAcesso = new ModelAcesso();
            modelAcesso.setNome("Cliente");
            modelAcesso.setIdkey("2");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro6 = jcbCliente2.getSelectedItem().toString();
            switch (filtro6) {
                case "S":
                    statusCliente = 1;
                    break;
                case "N":
                    statusCliente = 0;
                    break;
            }
            modelAcesso.setAuth(statusCliente);
            listaModelAcesso.add(modelAcesso);
            modelAcesso.setAuth(statusCliente);
            listaModelAcesso.add(modelAcesso);
            modelAcesso = new ModelAcesso();
            modelAcesso.setNome("Cliente");
            modelAcesso.setIdkey("3");
            modelAcesso.setIdperfil(Integer.parseInt(jtfID.getText()));
            String filtro7 = jcbCliente3.getSelectedItem().toString();
            switch (filtro7) {
                case "S":
                    statusCliente = 1;
                    break;
                case "N":
                    statusCliente = 0;
                    break;
            }
            modelAcesso.setAuth(statusCliente);
            listaModelAcesso.add(modelAcesso);

            codigoPerfil = controllerPerfil.salvarPerfilController(modelPerfil);
            if (codigoPerfil > 0) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a perfil", "Erro 1", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Perfil salvo com sucesso! 1", "Atenção", JOptionPane.WARNING_MESSAGE);
            }

            int proximo = Integer.parseInt(jtfID.getText());
            modelProximos.setIdkey(9);
            modelProximos.setProximo(proximo + 1);
            controllerProximos.atualizarSetProximosController(modelProximos);

            if (controllerAcesso.salvarListaAcessoController(listaModelAcesso)) {
                JOptionPane.showMessageDialog(this, "Perfil salvo com sucesso! 2", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar permissões", "Erro 2", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void setProximo() {
        jtfID.setText(String.valueOf(controllerProximos.getProximosController(9).getProximo()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox jcbCliente1;
    private javax.swing.JComboBox jcbCliente2;
    private javax.swing.JComboBox jcbCliente3;
    private javax.swing.JComboBox jcbConfig1;
    private javax.swing.JComboBox jcbConfig2;
    private javax.swing.JComboBox jcbConfig3;
    private javax.swing.JComboBox jcbConfig4;
    public static javax.swing.JComboBox jcbStatus;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfID;
    // End of variables declaration//GEN-END:variables
}
