/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Uppercase;
import static View.viewMainMenu.Desktop;
import controller.ControllerArea;
import controller.ControllerProximos;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.ModelArea;
import model.ModelProximos;
import Tools.BLDatas;

/**
 *
 * @author Maycon
 */
public class viewAltArea extends javax.swing.JInternalFrame {

    ControllerArea controllerArea = new ControllerArea();
    ModelArea modelArea = new ModelArea();
    ArrayList<ModelArea> listaModelArea = new ArrayList<>();

    ControllerProximos controllerProximos = new ControllerProximos();
    ModelProximos modelProximos = new ModelProximos();

    BLDatas bLDatas = new BLDatas();
    Uppercase uppercase = new Uppercase();

    /**
     * Creates new form viewAltArea
     */
    public viewAltArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfAreaNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jsNivel = new javax.swing.JSlider();

        jLabel1.setText("ID:");

        jtfID.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfID.setEnabled(false);

        jLabel2.setText("Descrição:");

        jLabel3.setText("Status:");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jLabel4.setText("Nível:");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jsNivel.setMajorTickSpacing(1);
        jsNivel.setMaximum(3);
        jsNivel.setMinimum(1);
        jsNivel.setMinorTickSpacing(1);
        jsNivel.setPaintLabels(true);
        jsNivel.setPaintTicks(true);
        jsNivel.setValue(0);
        jsNivel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsNivelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfID, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfAreaNome)
                            .addComponent(jsNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfAreaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jsNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        AlterarArea();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        viewMainUsuario.jTabbedPane1.setSelectedIndex(0);
        viewMainUsuario ViewMainUsuario = new viewMainUsuario();
        Desktop.add(ViewMainUsuario);
        centralizaForm(ViewMainUsuario);
        ViewMainUsuario.show();
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jsNivelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsNivelStateChanged

    }//GEN-LAST:event_jsNivelStateChanged

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    private void AlterarArea() {
        int status = 0;
        modelArea = controllerArea.getAreaVerificaDuplicidadeController(jtfAreaNome.getText());
        if (modelArea.getCount() > 0) {
            JOptionPane.showMessageDialog(this, "Já existe um cadastro com essa descrição. Por favor, verifique.!!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            modelArea.setIdarea(Integer.parseInt(jtfID.getText()));
            modelArea.setAreaNivel(jsNivel.getValue());
            modelArea.setAreaDescricao(uppercase.Uppercase(jtfAreaNome.getText()));
            modelArea.setDataalt(bLDatas.retornarData());
            modelArea.setUsuarioalt(viewMainMenu.lblUsuario.getText());
            String filtro = jcbStatus.getSelectedItem().toString();
            switch (filtro) {
                case "Ativo":
                    status = 1;
                    break;
                case "Inativo":
                    status = 0;
                    break;

            }
            modelArea.setAreaStatus(status);

            if (controllerArea.atualizarAreaController(modelArea)) {
                JOptionPane.showMessageDialog(this, "Área alterada no sistema!", "Sucesso", JOptionPane.WARNING_MESSAGE);
                viewMainUsuario ViewMainUsuario = new viewMainUsuario();
                viewMainMenu.Desktop.add(ViewMainUsuario);
                centralizaForm(ViewMainUsuario);
                ViewMainUsuario.show();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar área, verifique os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JComboBox jcbStatus;
    public static javax.swing.JSlider jsNivel;
    public static javax.swing.JTextField jtfAreaNome;
    public static javax.swing.JTextField jtfID;
    // End of variables declaration//GEN-END:variables
}
