/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.BLDatas;
import Tools.Forms;
import static View.viewMainMenu.Desktop;
import controller.ControllerProximos;
import controller.ControllerRoteiro;
import controller.ControllerTransportadora;
import javax.swing.JOptionPane;
import model.ModelProximos;
import model.ModelRoteiro;
import model.ModelTransportadora;

/**
 *
 * @author Maycon
 */
public class viewCadRoteiro extends javax.swing.JInternalFrame {

    ControllerTransportadora controllerTransportadora = new ControllerTransportadora();
    ModelTransportadora modelTransportadora = new ModelTransportadora();

    ControllerRoteiro controllerRoteiro = new ControllerRoteiro();
    ModelRoteiro modelRoteiro = new ModelRoteiro();

    ControllerProximos controllerProximos = new ControllerProximos();
    ModelProximos modelProximos = new ModelProximos();

    Forms forms = new Forms();
    BLDatas bLDatas = new BLDatas();

    /**
     * Creates new form viewCadRoteiro
     */
    public viewCadRoteiro() {
        initComponents();
        setProximo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDescRoteiro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfIdTransp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeTransp = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();

        setTitle("Roteiro");

        jLabel1.setText("ID:");

        jtfID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfID.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfID.setEnabled(false);

        jLabel2.setText("Descrição:");

        jLabel3.setText("Transportadora padrão:");

        jtfIdTransp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfIdTranspFocusLost(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ico/zoom.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jtfNomeTransp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfNomeTransp.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfNomeTransp.setEnabled(false);

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Status:");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfIdTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(jtfNomeTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfDescRoteiro))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescRoteiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfIdTransp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNomeTransp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdTranspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfIdTranspFocusLost
        String nomeTransp;
        int codigoEmpresa = Integer.parseInt(viewMainMenu.lblCodEmp.getText());
        if (!jtfIdTransp.getText().equals("")) {
            modelTransportadora = controllerTransportadora.getTransportadoraController(codigoEmpresa, Integer.parseInt(jtfIdTransp.getText()));
        } else {
            modelTransportadora.setTranspRaz(null);
        }

        if (jtfIdTransp.getText().equals("") || jtfIdTransp.getText() == null || modelTransportadora.getTranspRaz() == null) {
            JOptionPane.showMessageDialog(this, "O campo transportadora(ID) esta em branco!!", "Erro", JOptionPane.ERROR_MESSAGE);
            jtfNomeTransp.setText("Transportadora não encontrada!");
            jtfIdTransp.requestFocus();
            jtfIdTransp.setText("");
        } else {
            jtfNomeTransp.setText(modelTransportadora.getTranspRaz());
        }
    }//GEN-LAST:event_jtfIdTranspFocusLost

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        viewCadPesquisaTranspRoteiro ViewPesquisarTranspRoteiro = new viewCadPesquisaTranspRoteiro();
        Desktop.add(ViewPesquisarTranspRoteiro);
        forms.centralizaForm(ViewPesquisarTranspRoteiro);
        ViewPesquisarTranspRoteiro.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        salvarRoteiro();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        viewMainRoteiro ViewMainRoteiro = new viewMainRoteiro();
        Desktop.add(ViewMainRoteiro);
        forms.centralizaForm(ViewMainRoteiro);
        ViewMainRoteiro.show();
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void salvarRoteiro() {
        int status = 0;
        modelRoteiro = controllerRoteiro.getConsultarRoteiroController(jtfDescRoteiro.getText(), Integer.parseInt(viewMainMenu.lblCodEmp.getText()));

        if (modelRoteiro.getCount() > 0) {
            JOptionPane.showMessageDialog(this, "Já existe um Roteiro com essa descrição nesta empresa!!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            modelRoteiro.setIdroteiro(Integer.parseInt(jtfID.getText()));
            modelRoteiro.setEmpcod(Integer.parseInt(viewMainMenu.lblCodEmp.getText()));
            modelRoteiro.setRotDesc(jtfDescRoteiro.getText());
            modelRoteiro.setTranspPadrao(Integer.parseInt(jtfIdTransp.getText()));
            modelRoteiro.setDatacad(bLDatas.retornarData());
            modelRoteiro.setDataalt("");
            modelRoteiro.setUsuariocad(viewMainMenu.lblUsuario.getText());
            modelRoteiro.setUsuarioalt("");

            String filtro = jcbStatus.getSelectedItem().toString();
            switch (filtro) {
                case "Ativo":
                    status = 1;
                    break;
                case "Inativo":
                    status = 0;
                    break;
            }
            modelRoteiro.setRotStatus(status);

            int proximo = Integer.parseInt(jtfID.getText());
            modelProximos.setIdkey(11);
            modelProximos.setProximo(proximo + 1);
            controllerProximos.atualizarSetProximosController(modelProximos);

            if (controllerRoteiro.salvarRoteiroController(modelRoteiro) > 0) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar registro!!", "Erro", JOptionPane.ERROR_MESSAGE);

            } else {

                JOptionPane.showMessageDialog(this, "Roteiro salvo com sucesso!!", "Atenção", JOptionPane.WARNING_MESSAGE);
                viewMainRoteiro ViewMainRoteiro = new viewMainRoteiro();
                Desktop.add(ViewMainRoteiro);
                forms.centralizaForm(ViewMainRoteiro);
                ViewMainRoteiro.show();
                dispose();

            }

        }
    }

    private void setProximo() {
        jtfID.setText(String.valueOf(controllerProximos.getProximosController(11).getProximo()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JComboBox jcbStatus;
    public static javax.swing.JTextField jtfDescRoteiro;
    public static javax.swing.JTextField jtfID;
    public static javax.swing.JTextField jtfIdTransp;
    public static javax.swing.JTextField jtfNomeTransp;
    // End of variables declaration//GEN-END:variables
}
