/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.BLDatas;
import Tools.Forms;
import Tools.Uppercase;
import static View.viewMainMenu.Desktop;
import controller.ControllerEmpresa;
import controller.ControllerProximos;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.ModelEmpresa;
import model.ModelProximos;

/**
 *
 * @author Maycon
 */
public class viewCadEmpresa extends javax.swing.JInternalFrame {

    Forms forms = new Forms();
    Uppercase uppercase = new Uppercase();
    BLDatas bLDatas = new BLDatas();
    
    ControllerEmpresa controllerEmpresa = new ControllerEmpresa();
    ModelEmpresa modelEmpresa = new ModelEmpresa();
    
    ControllerProximos controllerProximos = new ControllerProximos();
    ModelProximos modelProximos = new ModelProximos();
    
    /**
     * Creates new form viewCadEmpresa
     */
    public viewCadEmpresa() {
        initComponents();
        visibilidadeConexao(false);
        comandoLicenca();
        setProximo();
        setDataCad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfRazaoSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeFantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfCNPJ = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfIE = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbStatusEmpresa = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtfPopEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfSmtpEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfLoginEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfSenhaEmail = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jtfPortaEmail = new javax.swing.JFormattedTextField();
        jcbStatusEmail = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jdcDiaVigente = new com.toedter.calendar.JDateChooser();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        Conexao = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtfLicencaQtd = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jdcDataExpiracao = new com.toedter.calendar.JDateChooser();
        jcbEstabelecimento = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfDataCadastro = new javax.swing.JFormattedTextField();

        setTitle("Setup - Cadastro Empresas");

        jLabel1.setText("ID:");

        jtfID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfID.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfID.setEnabled(false);

        jLabel2.setText("Razão Social:");

        jLabel3.setText("Nome Fantasia:");

        jLabel4.setText("CNPJ:");

        jLabel5.setText("I.E.:");

        jLabel7.setText("Status:");

        jcbStatusEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jLabel8.setText("POP:");

        jLabel9.setText("SMTP:");

        jLabel10.setText("LOGIN:");

        jLabel11.setText("SENHA:");

        jLabel12.setText("PORTA:");

        jtfPortaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPortaEmailActionPerformed(evt);
            }
        });

        jcbStatusEmail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        jLabel13.setText("Email Ativo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPopEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSenhaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jtfSmtpEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfPortaEmail)
                    .addComponent(jcbStatusEmail, 0, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfPopEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfPortaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbStatusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSmtpEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSenhaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Email", jPanel1);

        jLabel14.setText("Dia vigente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDiaVigente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcDiaVigente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Processamento", jPanel2);

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        Conexao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conexões", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        Conexao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConexaoKeyPressed(evt);
            }
        });

        jLabel16.setText("Licenças sistema:");

        jLabel17.setText("Expiração:");

        javax.swing.GroupLayout ConexaoLayout = new javax.swing.GroupLayout(Conexao);
        Conexao.setLayout(ConexaoLayout);
        ConexaoLayout.setHorizontalGroup(
            ConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConexaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLicencaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDataExpiracao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        ConexaoLayout.setVerticalGroup(
            ConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConexaoLayout.createSequentialGroup()
                .addGroup(ConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfLicencaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcDataExpiracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jcbEstabelecimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Padaria", "Mercearia", "Loja de Eletrônicos", "Assistência Técnica", "Loja de Roupas" }));

        jLabel15.setText("Área:");

        jLabel18.setText("Cadastro:");

        jtfDataCadastro.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfDataCadastro.setEnabled(false);
        jtfDataCadastro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCNPJ))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeFantasia))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRazaoSocial)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbStatusEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfIE)
                            .addComponent(jcbEstabelecimento, 0, 177, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jTabbedPane1)
            .addComponent(Conexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jcbEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbStatusEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Conexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar)
                    .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConexaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConexaoKeyPressed

    }//GEN-LAST:event_ConexaoKeyPressed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
        salvarUsuario();
        } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Verifique os dados. Possui alguma informação em branco!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        viewMainEmpresa ViewMainEmpresa = new viewMainEmpresa();
        Desktop.add(ViewMainEmpresa);
        forms.centralizaForm(ViewMainEmpresa);
        ViewMainEmpresa.show();
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtfPortaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPortaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPortaEmailActionPerformed

    private void visibilidadeConexao(boolean condicao) {
        Conexao.setVisible(condicao);
    }
    private void comandoLicenca() {
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK);

        Action actionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent evt) {

                if (!Conexao.isVisible()) {
                    Conexao.setVisible(true);
                } else {
                    Conexao.setVisible(false);
                }
            }
        };

        InputMap inputMap = this.getRootPane().getInputMap(
                JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ATIVA");

        this.getRootPane().getActionMap().put("ATIVA", actionListener);
    }
    private void salvarUsuario() {
        int statusEmail = 0,statusEmpresa = 0;
        modelEmpresa = controllerEmpresa.getValidarEmpresaController(jtfRazaoSocial.getText());

        if (modelEmpresa.getCount() > 0) {
            JOptionPane.showMessageDialog(this, "Já existe um usuário com esse Login!!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            modelEmpresa.setEmpCod(Integer.parseInt(jtfID.getText()));
            modelEmpresa.setEmpEstabelecimento(uppercase.Uppercase(String.valueOf(jcbEstabelecimento.getSelectedItem())));
            modelEmpresa.setEmpRazao(uppercase.Uppercase(jtfRazaoSocial.getText()));
            modelEmpresa.setEmpFantasia(uppercase.Uppercase(jtfNomeFantasia.getText()));
            modelEmpresa.setEmpCNPJ(jtfCNPJ.getText());
            modelEmpresa.setEmpIE(jtfIE.getText());
            
            int QtdLicenca = 0;
            if(jtfLicencaQtd.getText() == null){
                QtdLicenca = 1;
            }else{
                QtdLicenca = Integer.parseInt(jtfLicencaQtd.getText());
            }
            modelEmpresa.setEmpQtdLicenca(QtdLicenca);
            
            String dataExpiracao;
            if(String.valueOf(jdcDataExpiracao.getDate()) == null){
                dataExpiracao = bLDatas.formatarData(jdcDataExpiracao.getDate());
            }else{
                dataExpiracao = bLDatas.retornarData();
            }
            modelEmpresa.setEmpExpiracao(dataExpiracao);
            
            String filtro = jcbStatusEmail.getSelectedItem().toString();
            switch (filtro) {
                case "Sim":
                    statusEmail = 1;
                    break;
                case "Não":
                    statusEmail = 0;
                    break;
            }
            
            modelEmpresa.setEmpEmailStatus(statusEmail);
            modelEmpresa.setEmpEmailPorta(Integer.parseInt(jtfPortaEmail.getText()));
            modelEmpresa.setEmpEmailPop(jtfPopEmail.getText());
            modelEmpresa.setEmpEmailSmtp(jtfSmtpEmail.getText());
            modelEmpresa.setEmpEmailLogin(jtfLoginEmail.getText());
            modelEmpresa.setEmpEmailSenha(jtfSenhaEmail.getText());
            modelEmpresa.setEmpFechamentoDia(bLDatas.formatarData(jdcDiaVigente.getDate()));
           
            String filtro2 = jcbStatusEmpresa.getSelectedItem().toString();
            switch (filtro2) {
                case "Ativo":
                    statusEmpresa = 1;
                    break;
                case "Inativo":
                    statusEmpresa = 0;
                    break;
            }
            modelEmpresa.setEmpStatus(statusEmpresa);
            
            int proximo = Integer.parseInt(jtfID.getText());
            modelProximos.setIdkey(10);
            modelProximos.setProximo(proximo + 1);
            controllerProximos.atualizarSetProximosController(modelProximos);

            

            if (controllerEmpresa.salvarEmpresaController(modelEmpresa) > 0) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar registro!!", "Erro", JOptionPane.ERROR_MESSAGE);

            } else {

                JOptionPane.showMessageDialog(this, "Empresa salva com sucesso!!", "Atenção", JOptionPane.WARNING_MESSAGE);
                viewMainEmpresa ViewMainEmpresa = new viewMainEmpresa();
                Desktop.add(ViewMainEmpresa);
                forms.centralizaForm(ViewMainEmpresa);
                ViewMainEmpresa.show();
                dispose();
            }

        }
    }
    private void setProximo() {
        jtfID.setText(String.valueOf(controllerProximos.getProximosController(10).getProximo()));
    }
    private void setDataCad() {
        jtfDataCadastro.setText(bLDatas.retornarData());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Conexao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbEstabelecimento;
    private javax.swing.JComboBox jcbStatusEmail;
    private javax.swing.JComboBox jcbStatusEmpresa;
    private com.toedter.calendar.JDateChooser jdcDataExpiracao;
    private com.toedter.calendar.JDateChooser jdcDiaVigente;
    private javax.swing.JFormattedTextField jtfCNPJ;
    private javax.swing.JFormattedTextField jtfDataCadastro;
    private javax.swing.JTextField jtfID;
    private javax.swing.JFormattedTextField jtfIE;
    private javax.swing.JFormattedTextField jtfLicencaQtd;
    private javax.swing.JTextField jtfLoginEmail;
    private javax.swing.JTextField jtfNomeFantasia;
    private javax.swing.JTextField jtfPopEmail;
    private javax.swing.JFormattedTextField jtfPortaEmail;
    private javax.swing.JTextField jtfRazaoSocial;
    private javax.swing.JPasswordField jtfSenhaEmail;
    private javax.swing.JTextField jtfSmtpEmail;
    // End of variables declaration//GEN-END:variables
}
