/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Uppercase;
import controller.ControllerArea;
import controller.ControllerPerfil;
import controller.ControllerUsuario;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelArea;
import model.ModelPerfil;
import model.ModelUsuario;
import Tools.BLDatas;
import static View.viewMainMenu.lblPerfil;
import controller.ControllerAcesso;
import model.ModelAcesso;

/**
 *
 * @author Maycon
 */
public class viewMainUsuario extends javax.swing.JInternalFrame {

    ControllerUsuario controllerUsuario = new ControllerUsuario();
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();

    ControllerArea controllerArea = new ControllerArea();
    ModelArea modelArea = new ModelArea();
    ArrayList<ModelArea> listaModelArea = new ArrayList<>();

    ControllerPerfil controllerPerfil = new ControllerPerfil();
    ModelPerfil modelPerfil = new ModelPerfil();
    ArrayList<ModelPerfil> listaModelPerfil = new ArrayList<>();

    ControllerAcesso controllerAcesso = new ControllerAcesso();
    ModelAcesso modelAcesso = new ModelAcesso();

    ArrayList<ModelAcesso> listaModelAcesso = new ArrayList<>();

    BLDatas bLDatas = new BLDatas();
    Uppercase uppercase = new Uppercase();

    /**
     * Creates new form viewCadUsuario
     */
    public viewMainUsuario() {
        initComponents();
        carregarUsuario();
        carregarArea();
        carregarPerfil();
        TotalUsuarioCadastrados();
        AcessoPerfil("Configurações");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jbNovoUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbUsers = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jbAlterarUsuario = new javax.swing.JButton();
        jcbFiltroUsuario = new javax.swing.JComboBox();
        jtfPesquisarUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfCountRegU = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbArea = new javax.swing.JTable();
        jcbFiltroArea = new javax.swing.JComboBox();
        jtfPesquisarArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCountReg1 = new javax.swing.JTextField();
        jbNovoArea = new javax.swing.JButton();
        jbAlterarArea = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbPerfil = new javax.swing.JTable();
        jcbFiltroPerfil = new javax.swing.JComboBox();
        jtfPesquisarPerfil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCountReg2 = new javax.swing.JTextField();
        jbNovoPerfil = new javax.swing.JButton();
        jbAlterarPerfil = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Setup - Lista Usuários");

        jbNovoUsuario.setText("Novo");
        jbNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoUsuarioActionPerformed(evt);
            }
        });

        jtbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbUsers);
        if (jtbUsers.getColumnModel().getColumnCount() > 0) {
            jtbUsers.getColumnModel().getColumn(0).setResizable(false);
            jtbUsers.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtbUsers.getColumnModel().getColumn(1).setResizable(false);
            jtbUsers.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbUsers.getColumnModel().getColumn(2).setResizable(false);
            jtbUsers.getColumnModel().getColumn(3).setResizable(false);
            jtbUsers.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jButton4.setText("Excluir");
        jButton4.setToolTipText("Não é permitido excluir usuários devido ao histórico de movimentações.");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbAlterarUsuario.setText("Alterar");
        jbAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarUsuarioActionPerformed(evt);
            }
        });

        jcbFiltroUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome", "Login", "Status" }));

        jtfPesquisarUsuario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtfPesquisarUsuarioInputMethodTextChanged(evt);
            }
        });
        jtfPesquisarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarUsuarioKeyReleased(evt);
            }
        });

        jLabel1.setText("Total Cadastros:");

        jtfCountRegU.setEditable(false);
        jtfCountRegU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfCountRegU.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfCountRegU.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCountRegU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbFiltroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisarUsuario)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jbAlterarUsuario)
                    .addComponent(jbNovoUsuario)
                    .addComponent(jLabel1)
                    .addComponent(jtfCountRegU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuário", jPanel1);

        jtbArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Área", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbArea.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtbArea);
        if (jtbArea.getColumnModel().getColumnCount() > 0) {
            jtbArea.getColumnModel().getColumn(0).setResizable(false);
            jtbArea.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtbArea.getColumnModel().getColumn(1).setResizable(false);
            jtbArea.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbArea.getColumnModel().getColumn(2).setResizable(false);
            jtbArea.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jcbFiltroArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Área", "Status" }));

        jtfPesquisarArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarAreaKeyReleased(evt);
            }
        });

        jLabel2.setText("Total Cadastros:");

        jtfCountReg1.setEditable(false);
        jtfCountReg1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfCountReg1.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfCountReg1.setEnabled(false);

        jbNovoArea.setText("Novo");
        jbNovoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoAreaActionPerformed(evt);
            }
        });

        jbAlterarArea.setText("Alterar");
        jbAlterarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbFiltroArea, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisarArea, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCountReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterarArea)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltroArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarArea)
                    .addComponent(jbNovoArea)
                    .addComponent(jLabel2)
                    .addComponent(jtfCountReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Área", jPanel2);

        jtbPerfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Perfil", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPerfil.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtbPerfil);
        if (jtbPerfil.getColumnModel().getColumnCount() > 0) {
            jtbPerfil.getColumnModel().getColumn(0).setResizable(false);
            jtbPerfil.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtbPerfil.getColumnModel().getColumn(1).setResizable(false);
            jtbPerfil.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbPerfil.getColumnModel().getColumn(2).setResizable(false);
            jtbPerfil.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jcbFiltroPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Perfil", "Status" }));

        jtfPesquisarPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarPerfilKeyReleased(evt);
            }
        });

        jLabel3.setText("Total Cadastros:");

        jtfCountReg2.setEditable(false);
        jtfCountReg2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfCountReg2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCountReg2.setDisabledTextColor(new java.awt.Color(114, 181, 164));
        jtfCountReg2.setEnabled(false);

        jbNovoPerfil.setText("Novo");
        jbNovoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoPerfilActionPerformed(evt);
            }
        });

        jbAlterarPerfil.setText("Alterar");
        jbAlterarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jcbFiltroPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCountReg2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovoPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterarPerfil)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltroPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPerfil)
                    .addComponent(jbNovoPerfil)
                    .addComponent(jLabel3)
                    .addComponent(jtfCountReg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Perfil", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int linha = jtbUsers.getSelectedRow();

        try {

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir registro?", "Confirme", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (resposta) {
                case JOptionPane.YES_OPTION:

                    int codigoUsuario = (int) jtbUsers.getValueAt(linha, 0);

                    if (controllerUsuario.excluirUsuarioController(codigoUsuario)) {
                        JOptionPane.showMessageDialog(this, "Usuário excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
                        this.carregarUsuario();

                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir Usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }

                    break;
                case JOptionPane.NO_OPTION:

                    break;
                case JOptionPane.CLOSED_OPTION:

                    break;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoUsuarioActionPerformed
        viewCadUsuario ViewCadUsuario = new viewCadUsuario();
        viewMainMenu.Desktop.add(ViewCadUsuario);
        centralizaForm(ViewCadUsuario);
        ViewCadUsuario.show();
        dispose();
    }//GEN-LAST:event_jbNovoUsuarioActionPerformed

    private void jbAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarUsuarioActionPerformed
        AlterarUsuario();
    }//GEN-LAST:event_jbAlterarUsuarioActionPerformed

    private void jtfPesquisarUsuarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtfPesquisarUsuarioInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarUsuarioInputMethodTextChanged

    private void jtfPesquisarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarUsuarioKeyReleased
        PesquisaUsuario();
    }//GEN-LAST:event_jtfPesquisarUsuarioKeyReleased

    private void jbNovoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoAreaActionPerformed
        viewCadArea ViewCadArea = new viewCadArea();
        viewMainMenu.Desktop.add(ViewCadArea);
        centralizaForm(ViewCadArea);
        ViewCadArea.show();
        dispose();
    }//GEN-LAST:event_jbNovoAreaActionPerformed

    private void jbAlterarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarAreaActionPerformed
        AlterarArea();
    }//GEN-LAST:event_jbAlterarAreaActionPerformed

    private void jbNovoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoPerfilActionPerformed
        viewCadPerfil ViewCadPerfil = new viewCadPerfil();
        viewMainMenu.Desktop.add(ViewCadPerfil);
        centralizaForm(ViewCadPerfil);
        ViewCadPerfil.show();
        dispose();
    }//GEN-LAST:event_jbNovoPerfilActionPerformed

    private void jbAlterarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPerfilActionPerformed
        AlterarPerfil();
    }//GEN-LAST:event_jbAlterarPerfilActionPerformed

    private void jtfPesquisarAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarAreaKeyReleased
        PesquisaArea();
    }//GEN-LAST:event_jtfPesquisarAreaKeyReleased

    private void jtfPesquisarPerfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarPerfilKeyReleased
        PesquisaPerfil();
    }//GEN-LAST:event_jtfPesquisarPerfilKeyReleased

    private void AlterarArea() {
        String status = null;
        int filtro, linha;
        linha = this.jtbArea.getSelectedRow();
        try { // resolver isso
            int codigoArea = (int) this.jtbArea.getValueAt(linha, 0);

            //recuperar dados do banco
            modelArea = controllerArea.getAreaController(codigoArea);
            viewAltArea ViewAltArea = new viewAltArea();
            viewMainMenu.Desktop.add(ViewAltArea);
            centralizaForm(ViewAltArea);
            ViewAltArea.show();
            dispose();

            viewAltArea.jtfID.setText(String.valueOf(modelArea.getIdarea()));
            viewAltArea.jtfAreaNome.setText(String.valueOf(modelArea.getAreaDescricao()));
            viewAltArea.jsNivel.setValue(modelArea.getAreaNivel());
            filtro = modelArea.getAreaStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;
            }

            viewAltArea.jcbStatus.setSelectedItem(String.valueOf(status));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void AlterarPerfil() {
        String status = null;
        int filtro, linha;
        linha = this.jtbPerfil.getSelectedRow();
        try { // resolver isso
            int codigoPerfil = (int) jtbPerfil.getValueAt(linha, 0);

            //recuperar dados do banco
            modelPerfil = controllerPerfil.getPerfilController(codigoPerfil);
            viewAltPerfil ViewAltPerfil = new viewAltPerfil();
            viewMainMenu.Desktop.add(ViewAltPerfil);
            centralizaForm(ViewAltPerfil);
            ViewAltPerfil.show();
            dispose();

            viewAltPerfil.jtfID.setText(String.valueOf(modelPerfil.getIdperfil()));
            viewAltPerfil.jtfDescricao.setText(modelPerfil.getPerNome());

            filtro = modelPerfil.getStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;
            }
            viewAltPerfil.jcbStatus.setSelectedItem(String.valueOf(status));

            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 1, "Configurações");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbConfig1.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 2, "Configurações");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbConfig2.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 3, "Configurações");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbConfig3.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 4, "Configurações");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbConfig4.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 1, "Cliente");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbCliente1.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 2, "Cliente");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbCliente2.setSelectedItem(String.valueOf(status));
            modelAcesso = new ModelAcesso();
            modelAcesso = controllerAcesso.getAcessoAlterarController(codigoPerfil, 3, "Cliente");

            filtro = modelAcesso.getAuth();
            switch (filtro) {
                case 1:
                    status = "S";
                    break;
                case 0:
                    status = "N";
                    break;
            }
            viewAltPerfil.jcbCliente3.setSelectedItem(String.valueOf(status));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void TotalUsuarioCadastrados() {
        for (int y = 0; y < jtbUsers.getRowCount(); y++) {
            int somaLinhas = jtbUsers.getModel().getRowCount();
            jtfCountRegU.setText(Integer.toString(somaLinhas)); // total de funções distintas cadastrados
        }
    }

    private void PesquisaUsuario() {
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbUsers.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbUsers.setRowSorter(classificador);
        String texto = uppercase.Uppercase(jtfPesquisarUsuario.getText());
        String filtro = (String.valueOf(jcbFiltroUsuario.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Nome":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            case "Login":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
                break;
            case "Status":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 3));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }

    }

    private void PesquisaArea() {
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbArea.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbArea.setRowSorter(classificador);
        String texto = uppercase.Uppercase(jtfPesquisarArea.getText());
        String filtro = (String.valueOf(jcbFiltroArea.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Área":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            case "Status":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }

    }

    private void PesquisaPerfil() {
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbPerfil.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbPerfil.setRowSorter(classificador);
        String texto = uppercase.Uppercase(jtfPesquisarPerfil.getText());
        String filtro = (String.valueOf(jcbFiltroPerfil.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Perfil":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            case "Status":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }

    }

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = viewMainMenu.Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    private void AlterarUsuario() {
        String status = null;
        int filtro, linha;
        linha = this.jtbUsers.getSelectedRow();
        try { // resolver isso
            int codigoUsuario = (int) this.jtbUsers.getValueAt(linha, 0);

            //recuperar dados do banco
            modelUsuario = controllerUsuario.getUsuarioController(codigoUsuario);
            viewAltUsuario ViewAltUsuario = new viewAltUsuario();
            viewMainMenu.Desktop.add(ViewAltUsuario);
            centralizaForm(ViewAltUsuario);
            ViewAltUsuario.show();
            dispose();

            viewAltUsuario.jtfID.setText(String.valueOf(modelUsuario.getIduser()));
            viewAltUsuario.jtfEmail.setText(String.valueOf(modelUsuario.getEmail()));
            viewAltUsuario.jtfLogin.setText(String.valueOf(modelUsuario.getLogin()));
            viewAltUsuario.jtfNome.setText(String.valueOf(modelUsuario.getNome()));
            viewAltUsuario.jtfSenha.setText(String.valueOf(modelUsuario.getSenha()));
            viewAltUsuario.jdcAniversario.setDate(bLDatas.converterDataStringParaDate(modelUsuario.getAniversario()));
            viewAltUsuario.jcbArea.setSelectedItem(String.valueOf(controllerArea.getAreaController(modelUsuario.getArea()).getAreaDescricao()));
            viewAltUsuario.jcbPerfil.setSelectedItem(String.valueOf(controllerPerfil.getPerfilController(modelUsuario.getPerfil()).getPerNome()));

            filtro = modelUsuario.getStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;
            }

            viewAltUsuario.jcbStatus.setSelectedItem(String.valueOf(status));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarUsuario() {
        listaModelUsuario = controllerUsuario.getListaUsuarioController();

        DefaultTableModel modelo = (DefaultTableModel) jtbUsers.getModel();
        modelo.setNumRows(0);

        int cont = listaModelUsuario.size();
        String status = null;
        for (int i = 0; i < cont; i++) {

            int filtro = listaModelUsuario.get(i).getStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;

            }
            modelo.addRow(new Object[]{
                listaModelUsuario.get(i).getIduser(),
                listaModelUsuario.get(i).getNome(),
                listaModelUsuario.get(i).getLogin(),
                status

            });

        }
    }

    private void carregarArea() {
        listaModelArea = controllerArea.getListaAreaController();

        DefaultTableModel modelo = (DefaultTableModel) jtbArea.getModel();
        modelo.setNumRows(0);

        int cont = listaModelArea.size();
        String status = null;
        for (int i = 0; i < cont; i++) {

            int filtro = listaModelArea.get(i).getAreaStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;

            }
            modelo.addRow(new Object[]{
                listaModelArea.get(i).getIdarea(),
                listaModelArea.get(i).getAreaDescricao(),
                status

            });

        }
    }

    private void carregarPerfil() {
        listaModelPerfil = controllerPerfil.getListaPerfilController();

        DefaultTableModel modelo = (DefaultTableModel) jtbPerfil.getModel();
        modelo.setNumRows(0);

        int cont = listaModelPerfil.size();
        String status = null;
        for (int i = 0; i < cont; i++) {

            int filtro = listaModelPerfil.get(i).getStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;

            }
            modelo.addRow(new Object[]{
                listaModelPerfil.get(i).getIdperfil(),
                listaModelPerfil.get(i).getPerNome(),
                status

            });

        }
    }

    private void AcessoPerfil(String Menu) {
        String Perfil;

        Perfil = lblPerfil.getText();
        if ((controllerAcesso.getValidarAcessoController(Perfil, Menu, 1).getAuth() == 0)) {
            jbNovoUsuario.setEnabled(false);
            jbAlterarUsuario.setEnabled(false);
        }
        if ((controllerAcesso.getValidarAcessoController(Perfil, Menu, 2).getAuth() == 0)) {
            jbNovoArea.setEnabled(false);
            jbAlterarArea.setEnabled(false);
        }
        if ((controllerAcesso.getValidarAcessoController(Perfil, Menu, 3).getAuth() == 0)) {
            jbNovoPerfil.setEnabled(false);
            jbAlterarPerfil.setEnabled(false);
        }
        if ((controllerAcesso.getValidarAcessoController(Perfil, Menu, 4).getAuth() == 0)) {
            //Montar cadEmpresa
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAlterarArea;
    private javax.swing.JButton jbAlterarPerfil;
    private javax.swing.JButton jbAlterarUsuario;
    private javax.swing.JButton jbNovoArea;
    private javax.swing.JButton jbNovoPerfil;
    private javax.swing.JButton jbNovoUsuario;
    private javax.swing.JComboBox jcbFiltroArea;
    private javax.swing.JComboBox jcbFiltroPerfil;
    private javax.swing.JComboBox jcbFiltroUsuario;
    private javax.swing.JTable jtbArea;
    private javax.swing.JTable jtbPerfil;
    private javax.swing.JTable jtbUsers;
    private javax.swing.JTextField jtfCountReg1;
    private javax.swing.JTextField jtfCountReg2;
    private javax.swing.JTextField jtfCountRegU;
    private javax.swing.JTextField jtfPesquisarArea;
    private javax.swing.JTextField jtfPesquisarPerfil;
    private javax.swing.JTextField jtfPesquisarUsuario;
    // End of variables declaration//GEN-END:variables
}
