/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.BLDatas;
import Tools.Forms;
import Tools.Uppercase;
import controller.ControllerEmpresa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelEmpresa;

/**
 *
 * @author Maycon
 */
public class viewMainEmpresa extends javax.swing.JInternalFrame {

    Forms forms = new Forms();
    BLDatas bLDatas = new BLDatas();
    Uppercase uppercase = new Uppercase();
    
    ControllerEmpresa controllerEmpresa = new ControllerEmpresa();
    ModelEmpresa modelEmpresa = new ModelEmpresa();
    ArrayList<ModelEmpresa> listaModelEmpresa = new ArrayList<>();

    /**
     * Creates new form viewMainEmpresa
     */
    public viewMainEmpresa() {
        initComponents();
        carregarEmpresas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEmpresas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcbFiltroEmpresa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtfPesquisarEmpresa = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Setup - Lista Empresas");

        jtbEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Razão Social", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbEmpresas);
        if (jtbEmpresas.getColumnModel().getColumnCount() > 0) {
            jtbEmpresas.getColumnModel().getColumn(0).setResizable(false);
            jtbEmpresas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtbEmpresas.getColumnModel().getColumn(1).setResizable(false);
            jtbEmpresas.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtbEmpresas.getColumnModel().getColumn(2).setResizable(false);
            jtbEmpresas.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcbFiltroEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Razão Social", "Status" }));

        jLabel1.setText("Filtro:");

        jtfPesquisarEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarEmpresaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbFiltroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisarEmpresa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewCadEmpresa ViewCadEmpresa = new viewCadEmpresa();
        viewMainMenu.Desktop.add(ViewCadEmpresa);
        forms.centralizaForm(ViewCadEmpresa);
        ViewCadEmpresa.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        alterarEmpresa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linha = jtbEmpresas.getSelectedRow();

        try {

            int codigoEmpresa = (int) jtbEmpresas.getValueAt(linha, 0);
            if (codigoEmpresa > 0) {
                int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir registro?", "Confirme", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
                switch (resposta) {
                    case JOptionPane.YES_OPTION:

                        if (controllerEmpresa.excluirEmpresaController(codigoEmpresa)) {
                            JOptionPane.showMessageDialog(this, "Empresa excluída!", "Atenção", JOptionPane.WARNING_MESSAGE);
                            this.carregarEmpresas();

                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao excluir empresa! Existe movimentação para esta empresa", "ERRO", JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    case JOptionPane.NO_OPTION:

                        break;
                    case JOptionPane.CLOSED_OPTION:

                        break;
                }
            }else{
                  JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfPesquisarEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarEmpresaKeyReleased
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbEmpresas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbEmpresas.setRowSorter(classificador);
        String texto = uppercase.Uppercase(jtfPesquisarEmpresa.getText());
        String filtro = (String.valueOf(jcbFiltroEmpresa.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Razão Social":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            case "Status":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }
    }//GEN-LAST:event_jtfPesquisarEmpresaKeyReleased
    private void carregarEmpresas() {
        listaModelEmpresa = controllerEmpresa.getListaEmpresaController();

        DefaultTableModel modelo = (DefaultTableModel) jtbEmpresas.getModel();
        modelo.setNumRows(0);

        int cont = listaModelEmpresa.size();
        String status = null;
        for (int i = 0; i < cont; i++) {

            int filtro = listaModelEmpresa.get(i).getEmpStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;

            }
            modelo.addRow(new Object[]{
                listaModelEmpresa.get(i).getEmpCod(),
                listaModelEmpresa.get(i).getEmpRazao(),
                status

            });

        }
    }

    private void alterarEmpresa() {
        String status = null;
        int filtroStatusEmail, filtroStatusEmpresa, linha;
        linha = this.jtbEmpresas.getSelectedRow();
        try { // resolver isso
            int codigoEmpresa = (int) this.jtbEmpresas.getValueAt(linha, 0);

            //recuperar dados do banco
            modelEmpresa = controllerEmpresa.getEmpresaController(codigoEmpresa);
            viewAltEmpresa ViewAltEmpresa = new viewAltEmpresa();
            viewMainMenu.Desktop.add(ViewAltEmpresa);
            forms.centralizaForm(ViewAltEmpresa);
            ViewAltEmpresa.show();
            dispose();

            viewAltEmpresa.jtfID.setText(String.valueOf(modelEmpresa.getEmpCod()));
            viewAltEmpresa.jcbEstabelecimento.setSelectedItem(String.valueOf(modelEmpresa.getEmpEstabelecimento()));
            viewAltEmpresa.jtfRazaoSocial.setText(String.valueOf(modelEmpresa.getEmpRazao()));
            viewAltEmpresa.jtfNomeFantasia.setText(String.valueOf(modelEmpresa.getEmpFantasia()));
            viewAltEmpresa.jtfCNPJ.setText(String.valueOf(modelEmpresa.getEmpCNPJ()));
            viewAltEmpresa.jtfIE.setText(String.valueOf(modelEmpresa.getEmpIE()));
            viewAltEmpresa.jtfLicencaQtd.setText(String.valueOf(modelEmpresa.getEmpQtdLicenca()));
            viewAltEmpresa.jdcDataExpiracao.setDate(bLDatas.converterDataStringParaDate(modelEmpresa.getEmpExpiracao()));
            viewAltEmpresa.jtfDataCadastro.setText(bLDatas.addBarras(modelEmpresa.getCadastro()));
            viewAltEmpresa.jtfPopEmail.setText(String.valueOf(modelEmpresa.getEmpEmailPop()));
            filtroStatusEmail = modelEmpresa.getEmpEmailStatus();
            switch (filtroStatusEmail) {
                case 1:
                    status = "Sim";
                    break;
                case 0:
                    status = "Não";
                    break;
            }
            viewAltEmpresa.jcbStatusEmail.setSelectedItem(String.valueOf(status));
            viewAltEmpresa.jtfPortaEmail.setText(String.valueOf(modelEmpresa.getEmpEmailPorta()));
            viewAltEmpresa.jtfSmtpEmail.setText(String.valueOf(modelEmpresa.getEmpEmailSmtp()));
            viewAltEmpresa.jtfLoginEmail.setText(String.valueOf(modelEmpresa.getEmpEmailLogin()));
            viewAltEmpresa.jtfSenhaEmail.setText(String.valueOf(modelEmpresa.getEmpEmailSenha()));
            viewAltEmpresa.jdcDiaVigente.setDate(bLDatas.converterDataStringParaDate(modelEmpresa.getEmpFechamentoDia()));

            filtroStatusEmpresa = modelEmpresa.getEmpStatus();
            switch (filtroStatusEmpresa) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;
            }
            viewAltEmpresa.jcbStatusEmpresa.setSelectedItem(String.valueOf(status));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbFiltroEmpresa;
    private javax.swing.JTable jtbEmpresas;
    private javax.swing.JTextField jtfPesquisarEmpresa;
    // End of variables declaration//GEN-END:variables
}
