/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Forms;
import static View.viewMainMenu.Desktop;
import controller.ControllerRoteiro;
import controller.ControllerTransportadora;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelRoteiro;

/**
 *
 * @author Maycon
 */
public class viewMainRoteiro extends javax.swing.JInternalFrame {

    ControllerRoteiro controllerRoteiro = new ControllerRoteiro();
    ModelRoteiro modelRoteiro = new ModelRoteiro();
    ArrayList<ModelRoteiro> listaModelRoteiro = new ArrayList<>();

    ControllerTransportadora controllerTransportadora = new ControllerTransportadora();

    Forms forms = new Forms();

    /**
     * Creates new form viewCadRoteiro
     */
    public viewMainRoteiro() {
        initComponents();
        carregarRoteiro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbRoteiro = new javax.swing.JTable();
        jbInserir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes - Lista Roteiros");

        jLabel1.setText("Filtro:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Descrição", "Status" }));

        jtbRoteiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbRoteiro);
        if (jtbRoteiro.getColumnModel().getColumnCount() > 0) {
            jtbRoteiro.getColumnModel().getColumn(0).setResizable(false);
            jtbRoteiro.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtbRoteiro.getColumnModel().getColumn(1).setResizable(false);
            jtbRoteiro.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtbRoteiro.getColumnModel().getColumn(2).setResizable(false);
            jtbRoteiro.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 257, Short.MAX_VALUE)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbInserir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        viewCadRoteiro ViewCadRoteiro = new viewCadRoteiro();
        Desktop.add(ViewCadRoteiro);
        forms.centralizaForm(ViewCadRoteiro);
        ViewCadRoteiro.show();
        dispose();
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterarTransportadora();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int linha, codigoRoteiro, codigoEmpresa;
        linha = jtbRoteiro.getSelectedRow();
        codigoRoteiro = (int) jtbRoteiro.getValueAt(linha, 0);
        codigoEmpresa = Integer.parseInt(viewMainMenu.lblCodEmp.getText());
        
        try {

            if (codigoEmpresa > 0) {
                int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir registro?", "Confirme", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
                switch (resposta) {
                    case JOptionPane.YES_OPTION:

                        if (controllerTransportadora.excluirTransportadoraController(codigoEmpresa, codigoRoteiro)) {
                            JOptionPane.showMessageDialog(this, "Roteiro excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
                            carregarRoteiro();

                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao excluir roteiro! Existe movimentação deste parâmetro para esta empresa", "ERRO", JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    case JOptionPane.NO_OPTION:

                        break;
                    case JOptionPane.CLOSED_OPTION:

                        break;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro I/O, tente novamente!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void alterarTransportadora() {
        String status = null;
        int filtroStatus, linha, codigoRoteiro, codigoEmp;
        linha = this.jtbRoteiro.getSelectedRow();
        try { // resolver isso
            codigoRoteiro = (int) this.jtbRoteiro.getValueAt(linha, 0);
            codigoEmp = Integer.parseInt(viewMainMenu.lblCodEmp.getText());
            //recuperar dados do banco
            modelRoteiro = controllerRoteiro.getRoteiroEmpController(codigoEmp, codigoRoteiro);
            viewAltRoteiro ViewAltRoteiro = new viewAltRoteiro();
            viewMainMenu.Desktop.add(ViewAltRoteiro);
            forms.centralizaForm(ViewAltRoteiro);
            ViewAltRoteiro.show();
            dispose();

            viewAltRoteiro.jtfID.setText(String.valueOf(modelRoteiro.getIdroteiro()));
            viewAltRoteiro.jtfDescRoteiro.setText(modelRoteiro.getRotDesc());
            viewAltRoteiro.jtfIdTransp.setText(String.valueOf(modelRoteiro.getTranspPadrao()));
            viewAltRoteiro.jtfNomeTransp.setText(String.valueOf(controllerTransportadora.getTransportadoraController(codigoEmp, modelRoteiro.getTranspPadrao()).getTranspRaz()));
            
            filtroStatus = modelRoteiro.getRotStatus();
            switch (filtroStatus) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;
            }

            viewAltRoteiro.jcbStatus.setSelectedItem(String.valueOf(status));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarRoteiro() {
        listaModelRoteiro = controllerRoteiro.getListaRoteiroEmpController(Integer.parseInt(viewMainMenu.lblCodEmp.getText()));

        DefaultTableModel modelo = (DefaultTableModel) jtbRoteiro.getModel();
        modelo.setNumRows(0);

        int cont = listaModelRoteiro.size();
        String status = null;
        for (int i = 0; i < cont; i++) {

            int filtro = listaModelRoteiro.get(i).getRotStatus();
            switch (filtro) {
                case 1:
                    status = "Ativo";
                    break;
                case 0:
                    status = "Inativo";
                    break;

            }
            modelo.addRow(new Object[]{
                listaModelRoteiro.get(i).getIdroteiro(),
                listaModelRoteiro.get(i).getRotDesc(),
                status

            });

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JTable jtbRoteiro;
    // End of variables declaration//GEN-END:variables
}
