/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.ControllerTransportadora;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ModelTransportadora;

/**
 *
 * @author Maycon
 */
public class viewAltPesquisaTranspRoteiro extends javax.swing.JInternalFrame {

    ControllerTransportadora controllerTransportadora = new ControllerTransportadora();
    ModelTransportadora modelTransportadora = new ModelTransportadora();
    ArrayList<ModelTransportadora> listaModelTransportadora = new ArrayList<>();

    /**
     * Creates new form viewCadPesquisaTranspRoteiro
     */
    public viewAltPesquisaTranspRoteiro() {
        initComponents();
        carregarTransportadora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTransp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        jtbTransp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Transportadora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTransp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTranspMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTransp);
        if (jtbTransp.getColumnModel().getColumnCount() > 0) {
            jtbTransp.getColumnModel().getColumn(0).setResizable(false);
            jtbTransp.getColumnModel().getColumn(1).setResizable(false);
            jtbTransp.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jLabel1.setText("Filtro:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTranspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTranspMouseClicked
        int index = jtbTransp.getSelectedRow();

        Object id = jtbTransp.getValueAt(index, 0);
        Object cidade = jtbTransp.getValueAt(index, 1);
        viewAltRoteiro.jtfIdTransp.setText(String.valueOf(id));
        viewAltRoteiro.jtfNomeTransp.setText(String.valueOf(cidade));
        dispose();
    }//GEN-LAST:event_jtbTranspMouseClicked

    private void carregarTransportadora() {
        listaModelTransportadora = controllerTransportadora.getListaTransportadoraController(Integer.parseInt(viewMainMenu.lblCodEmp.getText()));
        DefaultTableModel modelo = (DefaultTableModel) jtbTransp.getModel();
        modelo.setNumRows(0);
        int cont = listaModelTransportadora.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelTransportadora.get(i).getTranspCod(),
                listaModelTransportadora.get(i).getTranspRaz()
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtbTransp;
    // End of variables declaration//GEN-END:variables
}
