/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.ControllerEmpresa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.ModelEmpresa;

/**
 *
 * @author Maycon
 */
public class viewMudarEmpresa extends javax.swing.JInternalFrame {

    ControllerEmpresa controllerEmpresa = new ControllerEmpresa();
    ModelEmpresa modelEmpresa = new ModelEmpresa();
    ArrayList<ModelEmpresa> listaModelEmpresa = new ArrayList<>();

    /**
     * Creates new form viewMudarEmpresa
     */
    public viewMudarEmpresa() {
        initComponents();
        carregarEmpresas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEmpresas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Selecionar empresa");

        jtbEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Razão Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbEmpresas);
        if (jtbEmpresas.getColumnModel().getColumnCount() > 0) {
            jtbEmpresas.getColumnModel().getColumn(0).setResizable(false);
            jtbEmpresas.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtbEmpresas.getColumnModel().getColumn(1).setResizable(false);
            jtbEmpresas.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 181, 164));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione a empresa clicando em cima.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbEmpresasMouseClicked
        int index = jtbEmpresas.getSelectedRow();
        TableModel model = jtbEmpresas.getModel();
        String id = model.getValueAt(index, 0).toString();
        viewMainMenu.lblCodEmp.setText(id);
        dispose();
    }//GEN-LAST:event_jtbEmpresasMouseClicked
    private void carregarEmpresas() {
        listaModelEmpresa = controllerEmpresa.getListaEmpresaAtivasController();

        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jtbEmpresas.getModel();
        modelo.setNumRows(0);

        int cont = listaModelEmpresa.size();
        for (int i = 0; i < cont; i++) {

            modelo.addRow(new Object[]{
                listaModelEmpresa.get(i).getEmpCod(),
                listaModelEmpresa.get(i).getEmpRazao()
            });

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbEmpresas;
    // End of variables declaration//GEN-END:variables
}
