/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Uppercase;
import controller.ControllerEstados;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelEstados;

/**
 *
 * @author Maycon
 */
public class viewAltPesquisarUFTransp extends javax.swing.JInternalFrame {

    ControllerEstados controllerEstados = new ControllerEstados();
    ModelEstados modelEstados = new ModelEstados();
    ArrayList<ModelEstados> listaModelEstados = new ArrayList<>();

    Uppercase uppercase = new Uppercase();

    /**
     * Creates new form ViewFuncaoCadPesquisaEstados
     */
    public viewAltPesquisarUFTransp() {
        initComponents();
        carregarEstados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEstados = new javax.swing.JTable();
        jtfPesquisar = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Pesquisar - Cidades");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtbEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbEstados.getTableHeader().setReorderingAllowed(false);
        jtbEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbEstadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbEstados);
        if (jtbEstados.getColumnModel().getColumnCount() > 0) {
            jtbEstados.getColumnModel().getColumn(0).setResizable(false);
            jtbEstados.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbEstados.getColumnModel().getColumn(1).setResizable(false);
            jtbEstados.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarActionPerformed(evt);
            }
        });
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Estado" }));

        jLabel1.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jbCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtbEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbEstadosMouseClicked
        int index = jtbEstados.getSelectedRow();

        Object id = jtbEstados.getValueAt(index, 0);
        Object cidade = jtbEstados.getValueAt(index, 1);
        viewAltTransp.jtfIdEstado.setText(String.valueOf(id));
        viewAltTransp.jtfNomeEstado.setText(String.valueOf(cidade));
        dispose();
    }//GEN-LAST:event_jtbEstadosMouseClicked

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        PesquisaEstados();
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void PesquisaEstados() {
        //filtrar na tabela
        DefaultTableModel modelo = (DefaultTableModel) jtbEstados.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        jtbEstados.setRowSorter(classificador);
        String texto = uppercase.Uppercase(jtfPesquisar.getText());
        String filtro = (String.valueOf(jcbFiltro.getSelectedItem()));
        switch (filtro) {
            case "ID":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
                break;
            case "Estado":
                classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
                break;
            default:
                classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        }

    }

    private void carregarEstados() {
        listaModelEstados = controllerEstados.getListaEstadosController();
        DefaultTableModel modelo = (DefaultTableModel) jtbEstados.getModel();
        modelo.setNumRows(0);
        int cont = listaModelEstados.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelEstados.get(i).getIdestado(),
                listaModelEstados.get(i).getNome()
            });
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbFiltro;
    private javax.swing.JTable jtbEstados;
    private javax.swing.JTextField jtfPesquisar;
    // End of variables declaration//GEN-END:variables
}
